version: 2

# build job parameters as a template
defaults: &defaults
  working_directory: ~/app
  docker:
    # the Docker image with Cypress dependencies
    - image: cypress/base:8
      environment:
        ## this enables colors in the output
        TERM: xterm

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: /root/app
          paths:
            - node_modules
            - cypress
            - cypress.json
            - index.html

  testA:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/app
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running E2E tests A
          command: $(npm bin)/cypress run --spec cypress/integration/a-spec.js --reporter junit --reporter-options "mochaFile=results/my-test-output.xml"
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots


  testB:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/app
      - run:
          name: Running E2E tests B
          command: $(npm bin)/cypress run --spec cypress/integration/b-spec.js --reporter junit --reporter-options "mochaFile=results/my-test-output.xml"
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - testA:
          requires:
            - build
      - testB:
          requires:
            - build